# true colours support                                                                                                              
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
# set -ga terminal-overrides ",*256col*:Tc"                                                                              

set -g pane-border-style fg="#16181D"
set -g pane-active-border-style "bg=default fg=#E06C75"

# set -g pane-border-fg "#16181D"
# set -g pane-active-border-fg "#E06C75"
# set -g pane-active-border-bg default

# set prefix
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# split panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# pane keybind
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# popup terminal
bind g display-popup -E -w 80% -h 80%
bind G display-popup -E -w 90% -h 90% nvim

set -g mouse on
set -s escape-time 0

bind r source-file ~/.tmux.conf

# apparance
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
