require("themery").setup({
	themes = {
		"coolTheme",
		"gruvbox",
		"retrobox",
		"vscode",
		"visual_studio_code",
		"onedark",
		"kanagawa-dragon",
		"github_dark",
		"github_dark_default",
		"github_dark_high_contrast",
		"github_dark_tritanopia",
		"catppuccin-latte",
		"catppuccin-frappe",
		"catppuccin-macchiato",
		"catppuccin-mocha",
	},
	livePreview = true,
})
