require("nvim-treesitter.configs").setup({
	highlight = { enable = true },
	indent = { enable = true },
	auto_install = { enable = true },
	folds = { enable = true }, ---@type lazyvim.TSFeat
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"css",
		"diff",
		"html",
		"javascript",
		"jsdoc",
		"json",
		"jsonc",
		"lua",
		"luadoc",
		"luap",
		"markdown",
		"markdown_inline",
		"printf",
		"python",
		"query",
		"regex",
		"toml",
		"tsx",
		"typescript",
		"vim",
		"vimdoc",
		"xml",
		"yaml",
	},
})

